tasty_bytes:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: 'not needed'
      user: 'not needed'
      role: accountadmin
      database: DS_DEV_DB
      schema: himanshu_dbt_db_dev
      warehouse: himanshu_dbt_wh
    prod:
      type: snowflake
      account: 'not needed'
      user: 'not needed'
      role: accountadmin
      database: DS_DEV_DB
      schema: himanshu_dbt_db_prod
      warehouse: himanshu_dbt_wh
